### ISSUE TITLE
OpenEphys.py to python3: "TypeError: 'str' does not support the buffer interface"

### ISSUE THREAD

**Issue by malfatti** [open-ephys/analysis-tools#18]
Hello!

I'm trying to load open-ephys files in python3. After 2to3 script conversion, when I try to load a .continuous file, I got this error:

```python
In [1]: import OpenEphys

In [2]: data = OpenEphys.load('100_CH1.continuous')
Loading continuous data...
Traceback (most recent call last):

  File "<ipython-input-2-e99a956d2fe5>", line 1, in <module>
    data = OpenEphys.load('100_CH1.continuous')

  File "/home/malfatti/Documents/SciScripts/Python3/Deps/OpenEphys/OpenEphys.py", line 39, in load
    data = loadContinuous(filepath)

  File "/home/malfatti/Documents/SciScripts/Python3/Deps/OpenEphys/OpenEphys.py", line 136, in loadContinuous
    header = readHeader(f)

  File "/home/malfatti/Documents/SciScripts/Python3/Deps/OpenEphys/OpenEphys.py", line 294, in readHeader
    h = f.read(1024).replace('\n','').replace('header.','')

TypeError: 'str' does not support the buffer interface
```

In line 134, f is defined as byte coding:
```python
f = open(filepath,'rb')
```
so I'm gessing that something in the readHeader function is not byte-encoded. I tried to use .encode() method in some strings (in line 294) but it didn't work.

Could you help me?

Cheers,
T Malfatti

**Comment by malfatti** [comment]
I fixed it. I just submitted a commit ([804372b](https://github.com/open-ephys/analysis-tools/pull/21)), suggesting the addition of a Python3 folder.
